services:
  vite-app:
    build: 
     context: .
     dockerfile: front/vue-project/Dockerfile
    ports:
      - "3000:80"

  clubs-back.api:
    container_name: clubs-back.api
    image: ${DOCKER_REGISTRY-}clubsbackapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7211
      - ASPNETCORE_HTTPS_PORTS=7210
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro  
    build:
      context: .
      dockerfile: ClubsBack/Dockerfile
    ports:
      - "7211:7211"
      - "7210:7210"
  