services:
  vite-app:
    build: 
     context: .
     dockerfile: front/vue-project/Dockerfile
    ports:
      - "3000:80"

  clubs-back.api:
    container_name: clubs-back.api
    image: ${DOCKER_REGISTRY-}bookstoreapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    build:
      context: .
      dockerfile: ClubsBack/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  